[package]
edition = "2021"
name = "bevy-frame"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
chrono = {version = "0.4.19", features = ["serde"]}
env_logger = "0.10.0"
log = "0.4.14"
