[package]
edition = "2021"
name = "bevy-frame"
version = "0.1.0"

[dependencies]
bevy = "0.11.3"
chrono = {version = "0.4.19", features = ["serde"]}
env_logger = "0.10.0"
log = "0.4.14"
perlin_noise = "1.0.1"
rand = "0.8.4"
